# Numpy, un vistazo simple al manejo de arrays

En este curso no vamos a adentrarnos en profundidad en el manejo de vectores y matrices. Sin embargo, trataremos de presentar algunos conceptos básicos. 

Principalmente, para seguir completando la idea de un "más allá" o "después" de los formatos tabulares.

Numpy es una librería que facilita amplias funcionalidades para el manejo de datos, y muchas veces vamos a verla como subsidiaria de pandas.

Sin embargo, tiene reglas propias y nos puede ayudar a resolver situaciones muy concretas.

## Formas de trabajar con un array

In [ ]:
import numpy as np

In [ ]:
# crear un array desde una lista
lista = [1,2,3]
a0 = np.array(lista)

In [ ]:
a0

array([1, 2, 3])

In [ ]:
# crear arrays desde numpy
a1 = np.random.randint(10, size=6)  
a2 = np.random.randint(10, size=(3, 4))  

In [ ]:
# creamos un array unidimensional con valores aleatorios de 0 a 10, de tamaño 6
a1

array([3, 6, 8, 5, 3, 6])

In [ ]:
# y otro bidimensional, de 3 * 4
a2

array([[3, 6, 2, 7],
       [7, 8, 7, 8],
       [8, 3, 3, 6]])

Entre los atributos de un array, encontramos: 

1. la cantidad de dimensiones 
2. la forma o shape (horizontal y verticalmente)
3. el tamaño (de cuanto por cuanto es el array):

In [ ]:
print("a2 ndim: ", a2.ndim)
print("a2 shape:", a2.shape)
print("a2 size: ", a2.size)

a2 ndim:  2
a2 shape: (3, 4)
a2 size:  12


Un array también se puede indexar. Es decir, acceder a elementos puntuales. 

In [ ]:
# tanto hacia adelante
a1

array([3, 6, 8, 5, 3, 6])

In [ ]:
a1[2]

8

In [ ]:
a1[5]

6

In [ ]:
# como hacia atras
a1[-1]

6

In [ ]:
a1[-3]

5

### ¿Qué tal si el array es multidimensional?

In [ ]:
# en ese caso, deberíamos indexar por ambos índices. Así
a2

array([[3, 6, 2, 7],
       [7, 8, 7, 8],
       [8, 3, 3, 6]])

In [ ]:
# el primer item del primer array
a2[0,0]

3

In [ ]:
# o el ultimo del primero
a2[0,3]

7

In [ ]:
# tambien el primer item del segundo array
a2[1,1]

8

## ¿Y podemos reemplazar valores?

In [ ]:
a2

array([[3, 6, 2, 7],
       [7, 8, 7, 8],
       [8, 3, 3, 6]])

In [ ]:
# efectivamente, valiendonos de la misma logica de indexado
a2[0,0] = 9

In [ ]:
a2

array([[9, 6, 2, 7],
       [7, 8, 7, 8],
       [8, 3, 3, 6]])

## Slicing y subarrays

In [ ]:
# tambien es posible acceder a secciones de un array, con algo que ya hemos mencionado: slicing
a1

array([3, 6, 8, 5, 3, 6])

In [ ]:
# accedemos del primer al tercer elemento
a1[0:3]

array([3, 6, 8])

In [ ]:
# o del primero al sexto de dos en dos
a1[0:6:2]

array([3, 8, 3])

El esquema sería el siguiente:

```x[start:stop:step]```

Y lo mismo aplica para arrays de mas de una dimension

In [ ]:
a2

array([[9, 6, 2, 7],
       [7, 8, 7, 8],
       [8, 3, 3, 6]])

In [ ]:
a2[0:2,2:4]

array([[2, 7],
       [7, 8]])

Numpy cuenta también con algunos método interesantes que no vienen en python de manera nativa. Por ejemplo, estadísticos descriptivos como media, mediana y desvío estándar.

In [ ]:
np.mean(a1)

5.166666666666667

In [ ]:
np.median(a1)

5.5

In [ ]:
np.std(a1)

1.7716909687891083